import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { GlobalProvider } from "@/context/GlobalContext";
import Navbar from "@/components/Navbar/Navbar";
// import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-sans">
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-grow">
            {/* <GlobalProvider>{children}</GlobalProvider> */}
            {children}
          </div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}